services:
  api:
    image: cactus-back
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "python manage.py makemigrations user &&
             python manage.py makemigrations snack &&
             python manage.py makemigrations lunch &&
             python manage.py makemigrations order &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15
    env_file:
      - .env.db
    ports:
      - "5432:5432"